name: ' CI/CD'

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/*.yaml'
      - '!.github/workflows/CICD.yaml'
    branches: [ 'main', 'release/*', 'feature/*' ]

defaults:
  run:
    shell: pwsh

permissions:
  contents: read
  actions: read

env:
  workflowDepth: 3
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Initialization:
    runs-on: [ ubuntu-latest ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
      environmentsMatrixJson: ${{ steps.DetermineDeploymentEnvironments.outputs.EnvironmentsMatrixJson }}
      environmentCount: ${{ steps.DetermineDeploymentEnvironments.outputs.EnvironmentCount }}
      deploymentEnvironmentsJson: ${{ steps.DetermineDeploymentEnvironments.outputs.DeploymentEnvironmentsJson }}
      deliveryTargetsJson: ${{ steps.DetermineDeliveryTargets.outputs.DeliveryTargetsJson }}
      githubRunner: ${{ steps.ReadSettings.outputs.GitHubRunnerJson }}
      githubRunnerShell: ${{ steps.ReadSettings.outputs.GitHubRunnerShell }}
      projects: ${{ steps.determineProjectsToBuild.outputs.ProjectsJson }}
      projectDependenciesJson: ${{ steps.determineProjectsToBuild.outputs.ProjectDependenciesJson }}
      buildOrderJson: ${{ steps.determineProjectsToBuild.outputs.BuildOrderJson }}
      workflowDepth: ${{ steps.DetermineWorkflowDepth.outputs.WorkflowDepth }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go/Actions/WorkflowInitialize@issue700
        with:
          shell: pwsh
          eventId: "DO0091"

      - name: Read settings
        id: ReadSettings
        uses: freddydk/AL-Go/Actions/ReadSettings@issue700
        with:
          shell: pwsh
          get: type

      - name: Determine Workflow Depth
        id: DetermineWorkflowDepth
        run: |
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "WorkflowDepth=$($env:workflowDepth)"

      - name: Determine Projects To Build
        id: determineProjectsToBuild
        uses: freddydk/AL-Go/Actions/DetermineProjectsToBuild@issue700
        with:
          shell: pwsh
          maxBuildDepth: ${{ env.workflowDepth }}

      - name: Determine Delivery Target Secrets
        id: DetermineDeliveryTargetSecrets
        uses: freddydk/AL-Go/Actions/DetermineDeliveryTargets@issue700
        with:
          shell: pwsh
          projectsJson: '${{ steps.determineProjectsToBuild.outputs.ProjectsJson }}'
          checkContextSecrets: 'N'

      - name: Read secrets
        id: ReadSecrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@issue700
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: ${{ steps.DetermineDeliveryTargetSecrets.outputs.ContextSecrets }}

      - name: Determine Delivery Targets
        id: DetermineDeliveryTargets
        uses: freddydk/AL-Go/Actions/DetermineDeliveryTargets@issue700
        env:
          Secrets: '${{ steps.ReadSecrets.outputs.Secrets }}'
        with:
          shell: pwsh
          projectsJson: '${{ steps.determineProjectsToBuild.outputs.ProjectsJson }}'
          checkContextSecrets: 'Y'

      - name: Determine Deployment Environments
        id: DetermineDeploymentEnvironments
        uses: freddydk/AL-Go/Actions/DetermineDeploymentEnvironments@issue700
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: pwsh
          getEnvironments: '*'
          type: 'CD'

  Deploy:
    needs: [ Initialization, Build ]
    if: always() && needs.Build.result == 'Success' && needs.Initialization.outputs.environmentCount > 0
    strategy: ${{ fromJson(needs.Initialization.outputs.environmentsMatrixJson) }}
    runs-on: ${{ fromJson(matrix.os) }}
    name: Deploy to ${{ matrix.environment }}
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: '.artifacts'

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@placeholders
        with:
          shell: pwsh

      - name: EnvName
        id: envName
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $envName = '${{ matrix.environment }}'.split(' ')[0]
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "envName=$envName"

      - name: Read secrets
        id: ReadSecrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@placeholders
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: '${{ steps.envName.outputs.envName }}-AuthContext,${{ steps.envName.outputs.envName }}_AuthContext,AuthContext,${{ steps.envName.outputs.envName }}-EnvironmentName,${{ steps.envName.outputs.envName }}_EnvironmentName,EnvironmentName,projects'

      - name: Deploy
        uses: freddydk/AL-Go/Actions/Deploy@placeholders
        env:
          Secrets: '${{ steps.ReadSecrets.outputs.Secrets }}'
        with:
          shell: pwsh
          environmentName: ${{ matrix.environment }}
          artifacts: '.artifacts'
          type: 'CD'
          deploymentEnvironmentsJson: ${{ needs.Initialization.outputs.deploymentEnvironmentsJson }}

  CheckForUpdates:
    runs-on: [ ubuntu-latest ]
    needs: [ Initialization ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@issue700
        with:
          shell: pwsh
          get: templateUrl

      - name: Check for updates to AL-Go system files
        uses: freddydk/AL-Go/Actions/CheckForUpdates@issue700
        with:
          shell: pwsh
          parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          templateUrl: ${{ env.templateUrl }}

  Build1:
    needs: [ Initialization ]
    if: (!failure()) && (!cancelled()) && fromJson(needs.Initialization.outputs.buildOrderJson)[0].projectsCount > 0
    strategy:
      matrix:
        include: ${{ fromJson(needs.Initialization.outputs.buildOrderJson)[0].buildDimensions }}
      fail-fast: false
    name: Build ${{ matrix.projectName }} (${{ matrix.buildMode }})
    uses: ./.github/workflows/_BuildALGoProject.yaml
    secrets: inherit
    with:
      shell: ${{ needs.Initialization.outputs.githubRunnerShell }}
      runsOn: ${{ needs.Initialization.outputs.githubRunner }}
      parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
      project: ${{ matrix.project }}
      projectName: ${{ matrix.projectName }}
      buildMode: ${{ matrix.buildMode }}
      projectDependenciesJson: ${{ needs.Initialization.outputs.projectDependenciesJson }}
      secrets: 'licenseFileUrl,insiderSasToken,codeSignCertificateUrl,*codeSignCertificatePassword,keyVaultCertificateUrl,*keyVaultCertificatePassword,keyVaultClientId,gitHubPackagesContext,applicationInsightsConnectionString'
      publishThisBuildArtifacts: ${{ needs.Initialization.outputs.workflowDepth > 1 }}
      publishArtifacts: ${{ github.ref_name == 'main' || startswith(github.ref_name, 'release/') || needs.Initialization.outputs.deliveryTargetsJson != '[]' || needs.Initialization.outputs.environmentCount > 0 }}
      signArtifacts: true
      useArtifactCache: true

  Build2:
    needs: [ Initialization, Build1 ]
    if: (!failure()) && (!cancelled()) && (needs.Build1.result == 'success' || needs.Build1.result == 'skipped') && fromJson(needs.Initialization.outputs.buildOrderJson)[1].projectsCount > 0
    strategy:
      matrix:
        include: ${{ fromJson(needs.Initialization.outputs.buildOrderJson)[1].buildDimensions }}
      fail-fast: false
    name: Build ${{ matrix.projectName }} (${{ matrix.buildMode }})
    uses: ./.github/workflows/_BuildALGoProject.yaml
    secrets: inherit
    with:
      shell: ${{ needs.Initialization.outputs.githubRunnerShell }}
      runsOn: ${{ needs.Initialization.outputs.githubRunner }}
      parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
      project: ${{ matrix.project }}
      projectName: ${{ matrix.projectName }}
      buildMode: ${{ matrix.buildMode }}
      projectDependenciesJson: ${{ needs.Initialization.outputs.projectDependenciesJson }}
      secrets: 'licenseFileUrl,insiderSasToken,codeSignCertificateUrl,*codeSignCertificatePassword,keyVaultCertificateUrl,*keyVaultCertificatePassword,keyVaultClientId,gitHubPackagesContext,applicationInsightsConnectionString'
      publishThisBuildArtifacts: ${{ needs.Initialization.outputs.workflowDepth > 1 }}
      publishArtifacts: ${{ github.ref_name == 'main' || startswith(github.ref_name, 'release/') || needs.Initialization.outputs.deliveryTargetsJson != '[]' || needs.Initialization.outputs.environmentCount > 0 }}
      signArtifacts: true
      useArtifactCache: true

  Build:
    needs: [ Initialization, Build2, Build1 ]
    if: (!failure()) && (!cancelled()) && (needs.Build2.result == 'success' || needs.Build2.result == 'skipped') && (needs.Build1.result == 'success' || needs.Build1.result == 'skipped') && fromJson(needs.Initialization.outputs.buildOrderJson)[2].projectsCount > 0
    strategy:
      matrix:
        include: ${{ fromJson(needs.Initialization.outputs.buildOrderJson)[2].buildDimensions }}
      fail-fast: false
    name: Build ${{ matrix.projectName }} (${{ matrix.buildMode }})
    uses: ./.github/workflows/_BuildALGoProject.yaml
    secrets: inherit
    with:
      shell: ${{ needs.Initialization.outputs.githubRunnerShell }}
      runsOn: ${{ needs.Initialization.outputs.githubRunner }}
      parentTelemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
      project: ${{ matrix.project }}
      projectName: ${{ matrix.projectName }}
      buildMode: ${{ matrix.buildMode }}
      projectDependenciesJson: ${{ needs.Initialization.outputs.projectDependenciesJson }}
      secrets: 'licenseFileUrl,insiderSasToken,codeSignCertificateUrl,*codeSignCertificatePassword,keyVaultCertificateUrl,*keyVaultCertificatePassword,keyVaultClientId,gitHubPackagesContext,applicationInsightsConnectionString'
      publishThisBuildArtifacts: ${{ needs.Initialization.outputs.workflowDepth > 1 }}
      publishArtifacts: ${{ github.ref_name == 'main' || startswith(github.ref_name, 'release/') || needs.Initialization.outputs.deliveryTargetsJson != '[]' || needs.Initialization.outputs.environmentCount > 0 }}
      signArtifacts: true
      useArtifactCache: true

  Deploy:
    needs: [ Initialization, Build ]
    if: always() && needs.Build.result == 'Success' && needs.Initialization.outputs.environmentCount > 0
    strategy: ${{ fromJson(needs.Initialization.outputs.environmentsMatrixJson) }}
    runs-on: ${{ fromJson(matrix.os) }}
    name: Deploy to ${{ matrix.environment }}
    environment:
      name: ${{ matrix.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: '.artifacts'

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@issue700
        with:
          shell: pwsh

      - name: EnvName
        id: envName
        run: |
          $errorActionPreference = "Stop"; $ProgressPreference = "SilentlyContinue"; Set-StrictMode -Version 2.0
          $envName = '${{ matrix.environment }}'.split(' ')[0]
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "envName=$envName"

      - name: Read secrets
        id: ReadSecrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@issue700
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: '${{ steps.envName.outputs.envName }}-AuthContext,${{ steps.envName.outputs.envName }}_AuthContext,AuthContext,${{ steps.envName.outputs.envName }}-EnvironmentName,${{ steps.envName.outputs.envName }}_EnvironmentName,EnvironmentName,projects'

      - name: Deploy
        uses: freddydk/AL-Go/Actions/Deploy@issue700
        env:
          Secrets: '${{ steps.ReadSecrets.outputs.Secrets }}'
        with:
          shell: pwsh
          environmentName: ${{ matrix.environment }}
          artifacts: '.artifacts'
          type: 'CD'
          deploymentEnvironmentsJson: ${{ needs.Initialization.outputs.deploymentEnvironmentsJson }}

  Deliver:
    needs: [ Initialization, Build ]
    if: always() && needs.Build.result == 'Success' && needs.Initialization.outputs.deliveryTargetsJson != '[]'
    strategy:
      matrix:
        deliveryTarget: ${{ fromJson(needs.Initialization.outputs.deliveryTargetsJson) }}
      fail-fast: false
    runs-on: [ ubuntu-latest ]
    name: Deliver to ${{ matrix.deliveryTarget }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: '.artifacts'

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@issue700
        with:
          shell: pwsh

      - name: Read secrets
        id: ReadSecrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@issue700
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: '${{ matrix.deliveryTarget }}Context'

      - name: Deliver
        uses: freddydk/AL-Go/Actions/Deliver@issue700
        env:
          Secrets: '${{ steps.ReadSecrets.outputs.Secrets }}'
        with:
          shell: pwsh
          type: 'CD'
          projects: ${{ needs.Initialization.outputs.projects }}
          deliveryTarget: ${{ matrix.deliveryTarget }}
          artifacts: '.artifacts'

  PostProcess:
    if: (!cancelled())
    runs-on: [ ubuntu-latest ]
    needs: [ Initialization, Build, Deploy, Deliver ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Finalize the workflow
        id: PostProcess
        uses: freddydk/AL-Go/Actions/WorkflowPostProcess@issue700
        with:
          shell: pwsh
          eventId: "DO0091"
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
