name: 'Create a new app'

run-name: "Create a new app in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      name:
        description: Name
        required: true      
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range (from..to)
        required: true
      sampleCode:
        description: Include Sample code (Y/N)
        required: false
        default: 'Y'
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: "N"
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for Pull Request/COMMIT
        type: boolean

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  CreateApp:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: mazhelez/AL-Go/Actions/WorkflowInitialize@fetch-artifacts-per-build-mode
        with:
          shell: pwsh
          eventId: "DO0092"

      - name: Read settings
        uses: mazhelez/AL-Go/Actions/ReadSettings@fetch-artifacts-per-build-mode
        with:
          shell: pwsh
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          get: type,keyVaultName,ghTokenWorkflowSecretName

      - name: Read secrets
        uses: mazhelez/AL-Go/Actions/ReadSecrets@fetch-artifacts-per-build-mode
        if: github.event.inputs.useGhTokenWorkflow == 'true'
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          shell: pwsh
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          settingsJson: ${{ env.Settings }}
          secrets: 'ghTokenWorkflow=${{ env.GHTOKENWORKFLOWSECRETNAME }}'

      - name: CalculateToken
        id: CalculateToken
        env:
          useGhTokenWorkflow: ${{ github.event.inputs.useGhTokenWorkflow }}
        run: |
          if ($env:useGhTokenWorkflow -eq 'true') {
            $ghToken = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:GHTOKENWORKFLOW))
          } else {
            $ghToken = '${{ secrets.GITHUB_TOKEN }}'
          }
          Add-Content -Path $env:GITHUB_OUTPUT -Value "ghToken=$ghToken"

      - name: Creating a new app
        uses: mazhelez/AL-Go/Actions/CreateApp@fetch-artifacts-per-build-mode
        with:
          shell: pwsh
          token: ${{ steps.CalculateToken.outputs.ghToken }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          type: ${{ env.type }}
          name: ${{ github.event.inputs.name }}
          publisher: ${{ github.event.inputs.publisher }}
          idrange: ${{ github.event.inputs.idrange }}
          sampleCode: ${{ github.event.inputs.sampleCode }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: mazhelez/AL-Go/Actions/WorkflowPostProcess@fetch-artifacts-per-build-mode
        with:
          shell: pwsh
          eventId: "DO0092"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
