name: ' Increment Version Number'

run-name: "Increment Version Number in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects (* for all projects)
        required: false
        default: '*'
      versionNumber:
        description: Updated Version Number. Use Major.Minor for absolute change, use +Major.Minor for incremental change.
        required: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for PR/Commit?
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  IncrementVersionNumber:
    needs: [ ]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Input
        if: github.event_name == 'workflow_dispatch'
        run: |
          Write-Host "Inputs:"
          $eventPath = Get-Content -Encoding UTF8 -Path $env:GITHUB_EVENT_PATH -Raw | ConvertFrom-Json
          $eventPath.inputs.psObject.Properties | Sort-Object { $_.Name } | ForEach-Object {
            $property = $_.Name
            $value = $eventPath.inputs."$property"
            Write-Host "- $property = '$value'"
          }

      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go/Actions/WorkflowInitialize@placeholders
        with:
          shell: pwsh
          eventId: "DO0096"

      - name: Read settings
        uses: freddydk/AL-Go/Actions/ReadSettings@placeholders
        with:
          shell: pwsh

      - name: Read secrets
        id: ReadSecrets
        uses: freddydk/AL-Go/Actions/ReadSecrets@placeholders
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'TokenForPush'
          useGhTokenWorkflowForPush: '${{ github.event.inputs.useGhTokenWorkflow }}'

      - name: Increment Version Number
        uses: freddydk/AL-Go/Actions/IncrementVersionNumber@placeholders
        with:
          shell: pwsh
          token: ${{ steps.ReadSecrets.outputs.TokenForPush }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          versionNumber: ${{ github.event.inputs.versionNumber }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: freddydk/AL-Go/Actions/WorkflowPostProcess@placeholders
        with:
          shell: pwsh
          eventId: "DO0096"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
